# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baf7c9aa1977c39d0a4f60b00f1080cc5408f039fb15941f79f0e1df3c7ba2819ec99b7f0336410b7f7f0479487654d72cf68aba08592bd46098ee19e758bbcc

test:
  secret_key_base: c8c0fc6fc376e292f5823b4b0c1631af7fe6f72b9b8c4df9173f692a9fe5c24a608733122e4b08924fabee7a9e34a468fd87c818df67ee67a69d8ab35afc8724

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
